stages:
  # prepare_input:
  #   cmd: >-
  #     echo "prepare input" &&
  #     echo "dlsc ..." &&
  #     echo "cdgen ..." && 
  #     echo "management ..."
  #   outs:
  #     - data/modeldrivers

  # run_simulations:
  #   cmd: >-
  #     # do this in on a big machine (bio11)
  #     # ...
  #     echo "ldndc ..."
  #   deps:
  #     - data/modeldrivers
  #   outs:
  #     - data/modeloutput

  # postprocess_netcdf:
  #   cmd: >-
  #     echo "ldndc2nc"
  #   deps:
  #     - data/modeloutput
  #   outs:
  #     - data/intermediate

  postprocess_aggregate:
    cmd: >-
      mkdir data/intermediate;
      python scripts/postprocess_aggregate.py data/raw/modeloutput data/intermediate data/raw/misc/VN_MISC5_V3.nc
    deps:
      - data/raw/modeloutput
      - data/raw/misc/VN_MISC5_V3.nc
    outs:
      - data/intermediate

  analysis_relaimpo:
    cmd: >-
      papermill nbs/relaimpo.ipynb - --progress-bar 1> /dev/null
    deps:
      - data/intermediate
      - data/raw/misc
    outs:
      - data/analysis/relaimpo
  
  # analysis_summary_stats:
  #   cmd: >-
  #     echo "scripts/summary_stats.py"
  #   deps:
  #     - data/aggregated
  #   outs:
  #     - data/analysis/summary_stats.json

  analysis_plots:
    cmd: >-
      papermill nbs/plots_maps.ipynb - --progress-bar 1> /dev/null
    deps:
      - data/intermediate
      - data/raw/misc
    outs:
      - data/analysis/plots

  paper_plots:
    cmd: >-
      mkdir data/paper;
      cp data/analysis/plots/emissions_merged_ch4_n2o_gwp.png data/paper/fig3_emissions_merged_ch4_n2o_gwp.png;
      cp data/analysis/plots/emissions_merged_yield_yieldscaled.png data/paper/fig6_emissions_merged_yield_yieldscaled_gwp.png;
      cp data/analysis/plots/emissions_riceonly_ch4_n2o_gwp.png data/paper/figS1_emissions_riceonly_ch4_n2o_gwp.png;
      cp data/analysis/plots/emissions_riceonly_yield_yieldscaled.png data/paper/figS3_emissions_riceonly_yield_yieldscaled_gwp.png;
      cp data/analysis/plots/emissions_seasonal_mekong.png data/paper/fig4_emissions_seasonal_mekong.png;
      cp data/analysis/plots/emissions_seasonal_redriver.png data/paper/figS2_emissions_seasonal_redriver.png;
      cp data/analysis/plots/management.png data/paper/fig1_management.png;
      cp data/analysis/relaimpo/relaimpo.png data/paper/fig5_relaimpo.png;
      cd data; tar cvfz paper.tgz paper; rm -Rf paper; cd ..
    deps:
      - data/analysis/plots
      - data/analysis/relaimpo
    outs:
      - data/paper.tgz 