stages:
  # prepare_input:
  #   cmd: >-
  #     echo "prepare input" &&
  #     echo "dlsc ..." &&
  #     echo "cdgen ..." && 
  #     echo "management ..."
  #   outs:
  #     - data/modeldrivers

  # run_simulations:
  #   cmd: >-
  #     # do this in on a big machine (bio11)
  #     # ...
  #     echo "ldndc ..."
  #   deps:
  #     - data/modeldrivers
  #   outs:
  #     - data/modeloutput

  # postprocess_netcdf:
  #   cmd: >-
  #     echo "ldndc2nc"
  #   deps:
  #     - data/modeloutput
  #   outs:
  #     - data/intermediate

  postprocess_aggregate:
    cmd: >-
      mkdir data/intermediate;
      python scripts/postprocess_aggregate.py data/raw/modeloutput data/intermediate data/raw/misc/VN_MISC5_V3.nc
    deps:
      - data/raw/modeloutput
      - data/raw/misc/VN_MISC5_V3.nc
    outs:
      - data/intermediate

  analysis_relaimpo:
    cmd: >-
      papermill nbs/relaimpo.ipynb - --progress-bar 1> /dev/null
    deps:
      - data/intermediate
      - data/raw/misc
    outs:
      - data/analysis/relaimpo
  
  # analysis_summary_stats:
  #   cmd: >-
  #     echo "scripts/summary_stats.py"
  #   deps:
  #     - data/aggregated
  #   outs:
  #     - data/analysis/summary_stats.json

  analysis_plots:
    cmd: >-
      papermill nbs/plots_maps.ipynb - --progress-bar 1> /dev/null
    deps:
      - data/intermediate
      - data/raw/misc
    outs:
      - data/analysis/plots
